title: Rohit Patel
email: rohit.patel061@gmail.com
description: "Full Stack Developer | ROR | Javascript | React | Vue"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rohitpatel061
github_username:  rohitcy

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5
comments: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
